hw6
Letruk190/kafka-homework pull request #6
Opened 2024-12-15 17:25 UTC by Letruk190

2024-12-17 19:42 UTC, mirzamax commented on hw6/clients-smt.json
> +    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
для захвата изменений данных используйте Debezium PostgreSQL CDC Source Connector

2024-12-17 19:46 UTC, mirzamax requested changes
Пожалуйста, используйте Debezium PostgreSQL CDC Source Connector для захвата изменений данных

2024-12-18 05:54 UTC, Letruk190 commented on hw6/clients-smt.json
> +    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
выполнил еще один пример с дебезиумом

2024-12-18 06:10 UTC, mirzamax approved these changes

2024-12-18 06:15 UTC, merged